# Generated by Django 4.2.6 on 2023-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0003_post_title_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="uncategorized", max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(max_length=200),
        ),
    ]
