# Generated by Django 4.2.6 on 2023-10-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0005_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.TextField(default="I love this post"),
            preserve_default=False,
        ),
    ]
