# Generated by Django 4.2.6 on 2023-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="hello", editable=False, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
