# Generated by Django 4.2.6 on 2023-10-28 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0013_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
